### PR TITLE
Add exports for client and config

### PR DESCRIPTION
**Pull request by daffl**
I think it would be nice to be able to access the client and config directly through the export so that it is possible to retrieve the profile outside of a middleware.

### CODE REVIEW

**Comment by simov** [comment]
Hi @daffl, I know that you are working on another OSS project, that you want to integrate Grant into. So my best bet is that I'm missing something, as you are not providing any background information, but here is my reasoning:

Initially I was going to create a _generic_ HTTP client that handles all the quirks around getting the user profiles. Then this middleware was going to consume it. And obviously I didn't got anywhere near finishing it.

Then you came in with your proposal in Grant, and I liked the idea that you are focusing specifically on how Grant is implemented. That clearly makes the HTTP client simpler, at the expense of making it tightly coupled with Grant.

So in it's current state I don't consider this internal client public. It depends on what Grant generates as configuration, and response.

As for the config itself, having only the config is not that useful either, I mean if it was not about the quirks, you wouldn't even need a custom client to begin with.

**Comment by daffl** [comment]
I'm using the client for letting users authenticate with an existing oAuth (usually v2) token. This is useful for e.g. mobile applications where you don't go through the browser flow but instead use e.g. the Facebook SDK to authenticate and it gives you back an access token.

**Comment by daffl** [comment]
Your call though. I'm using it with `require('grant-profile/lib/client`)` right now and everything is working well so this PR is not super essential.

**Comment by simov** [comment]
Thanks for the understanding, @daffl, like I said earlier I just don't want to commit to exposing this interface at the moment. That being said the location of the client `require('grant-profile/lib/client)` most likely won't going to change ever, so it should be pretty safe to use that.

**Comment by simov** [comment]
:wave: @daffl note that in v0.0.5 I renamed the internal `url` config key to `profile_url`. Also now the users can pass this additional key for any provider in their Grant configuration.

**Pull request closed without merging**
